name: Nodejs Typescript CD
on:
  workflow_run:
    workflows: ["Check & Create PR"]
    types:
      - completed
  push:
    branches:
      - dev
      - homolog
      - prod
jobs:
  DeployToAWS:
    environment:
      name: ${{ github.ref }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Setup AWS Credentials
        run: |
          echo "Configuring AWS Credentials"
          aws configure set aws_access_key_id ${{ vars.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ vars.AWS_SECRET_ACCESS_KEY_ID }}
          aws configure set default.region ${{ vars.REGION }}
          aws configure set default.output json
      - name: Setting stage, stack name
        run: |
          echo "STAGE=${{ vars.STAGE }}" >> $GITHUB_ENV
          echo "STACK_NAME=${{ vars.STACK_NAME }}-${{ github.ref_name }}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Installing Dependencies
        run: |
          yarn
          cd iac
          npm install -g aws-cdk
          npm i
      - name: Setup envs
        run: |
          echo STAGE=${{ vars.STAGE }} >> $GITHUB_ENV
          echo REGION=${{ vars.REGION }} >> $GITHUB_ENV
          echo AWS_ACCOUNT_ID=${{ vars.AWS_ACCOUNT_ID }} >> $GITHUB_ENV
          echo AWS_ACCESS_KEY_ID=${{ vars.AWS_ACCESS_KEY_ID }} >> $GITHUB_ENV
          echo AWS_SECRET_ACCESS_KEY=${{ vars.AWS_SECRET_ACCESS_KEY_ID }} >> $GITHUB_ENV
          echo STACK_NAME=${{ vars.STACK_NAME }} >> $GITHUB_ENV
          echo GITHUB_REF_NAME=${{ github.ref_name }} >> $GITHUB_ENV
          echo DYNAMO_TABLE_NAME=${{ vars.DYNAMO_TABLE_NAME }} >> $GITHUB_ENV
          echo DYNAMO_TABLE_NAME_HISTORY=${{ vars.DYNAMO_TABLE_NAME_HISTORY }} >> $GITHUB_ENV
      - name: CDK Bootstrap
        run: |
          echo "CDK Bootstrap"
          cd iac
          aws cloudformation describe-stacks --stack-name CDKToolkit 2>&1 > /dev/null || \
            cdk bootstrap aws://${{ vars.AWS_ACCOUNT_ID }}/sa-east-1
      - name: Deploy with CDK
        run: |
          source $GITHUB_ENV
          yarn build
          cd iac          
          cdk synth
          cdk deploy --require-approval never
        env:
          STAGE: ${{ vars.STAGE }}
          AWS_ACCESS_KEY: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ vars.AWS_SECRET_ACCESS_KEY_ID }}
          REGION: ${{ vars.REGION }}
          STACK_NAME: ${{ vars.STACK_NAME }}-${{ github.ref_name }}
          DYNAMO_TABLE_NAME: ${{ vars.DYNAMO_TABLE_NAME }}
          DYNAMO_TABLE_NAME_HISTORY: ${{ vars.DYNAMO_TABLE_NAME_HISTORY }}